In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import pprint
import json
from time import sleep
from datetime import date
from sqlalchemy import create_engine
import os
from glob import glob

# Output File location
output_folder = "output_data"

In [2]:
# Load data - Big Dance
rawdf_BigDance = pd.read_csv('Big_Dance_CSV.csv', low_memory=False)
rawdf_cbb = pd.read_csv('cbb.csv', low_memory=False)
rawdf_cbb15 = pd.read_csv('cbb15.csv', low_memory=False)
rawdf_cbb16 = pd.read_csv('cbb16.csv', low_memory=False)
rawdf_cbb17 = pd.read_csv('cbb17.csv', low_memory=False)
rawdf_cbb18 = pd.read_csv('cbb18.csv', low_memory=False)
rawdf_cbb19 = pd.read_csv('cbb19.csv', low_memory=False)

# EDA - Big Dance

In [3]:
rows_in_df = len(rawdf_BigDance)
print(f'Big Dance set has {rows_in_df} rows')
rawdf_BigDance.head(5)

Big Dance set has 2205 rows

,Year,Round,Region Number,Region Name,Seed,Score,Team,Team.1,Score.1,Seed.1
0,1985,1,1,West,1,83,St Johns,Southern,59,16
1,1985,1,1,West,2,81,VCU,Marshall,65,15
2,1985,1,1,West,3,65,NC State,Nevada,56,14
3,1985,1,1,West,4,85,UNLV,San Diego St,80,13
4,1985,1,1,West,5,58,Washington,Kentucky,65,12

In [4]:
rawdf_BigDance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 10 columns):
Year             2205 non-null int64
Round            2205 non-null int64
Region Number    2205 non-null int64
Region Name      2205 non-null object
Seed             2205 non-null int64
Score            2205 non-null int64
Team             2205 non-null object
Team.1           2205 non-null object
Score.1          2205 non-null int64
Seed.1           2205 non-null int64
dtypes: int64(7), object(3)
memory usage: 172.4+ KB

In [5]:
rawdf_BigDance.describe()

,Year,Round,Region Number,Seed,Score,Score.1,Seed.1
count,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000
mean,2002.000000,1.904762,2.444444,3.887528,74.304308,68.051701,9.474830
std,10.101796,1.191698,1.123993,2.900662,12.753399,12.295443,4.138256
min,1985.000000,1.000000,1.000000,1.000000,32.000000,29.000000,1.000000
25%,1993.000000,1.000000,1.000000,2.000000,65.000000,59.000000,6.000000
50%,2002.000000,1.000000,2.000000,3.000000,74.000000,67.000000,10.000000
75%,2011.000000,2.000000,3.000000,6.000000,82.000000,76.000000,13.000000
max,2019.000000,6.000000,4.000000,16.000000,131.000000,149.000000,16.000000

In [6]:
# Only 2015+ data
combineddf = rawdf_BigDance[rawdf_BigDance["Year"] >= 2015]
combineddf.columns

Index(['Year', 'Round', 'Region Number', 'Region Name', 'Seed', 'Score',
       'Team', 'Team.1', 'Score.1', 'Seed.1'],
      dtype='object')

In [7]:
combineddf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 315 entries, 1890 to 2204
Data columns (total 10 columns):
Year             315 non-null int64
Round            315 non-null int64
Region Number    315 non-null int64
Region Name      315 non-null object
Seed             315 non-null int64
Score            315 non-null int64
Team             315 non-null object
Team.1           315 non-null object
Score.1          315 non-null int64
Seed.1           315 non-null int64
dtypes: int64(7), object(3)
memory usage: 27.1+ KB

In [8]:
combineddf = combineddf.rename(columns={
    "Seed":    "Home_Seed"
    , "Score":   "Home_Score"
    , "Team":    "Home_Team" 
    , "Team.1":  "Away_Team" 
    , "Score.1": "Away_Score"
    , "Seed.1":   "Away_Seed" 
})
combineddf["Conference"] = "tbd! join w other data"

In [9]:
combineddf.head()

,Year,Round,Region Number,Region Name,Home_Seed,Home_Score,Home_Team,Away_Team,Away_Score,Away_Seed,Conference
1890,2015,1,1,Midwest,1,79,Kentucky,Hampton,56,16,tbd! join w other data
1891,2015,1,1,Midwest,2,75,Kansas,New Mexico St,56,15,tbd! join w other data
1892,2015,1,1,Midwest,3,69,Notre Dame,Northeastern,65,14,tbd! join w other data
1893,2015,1,1,Midwest,4,65,Maryland,Valparaiso,62,13,tbd! join w other data
1894,2015,1,1,Midwest,5,68,West Virginia,Buffalo,62,12,tbd! join w other data

In [10]:
#tried to merge all the csv files at once with glob...failed!
# stock_files=sorted(glob(college-basketball-dataset/cbb*.csv))
# stock_files

In [11]:
merge_table = pd.merge(rawdf_cbb19, rawdf_cbb18, on="TEAM")
merge_table2=pd.merge(merge_table, rawdf_cbb17, on="TEAM")
merge_table3=pd.merge(merge_table2, rawdf_cbb16, on="TEAM")
merge_table4=pd.merge(merge_table3, rawdf_cbb15, on="TEAM")
merge_table4

,TEAM,CONF_x,G_x,W_x,ADJOE_x,ADJDE_x,BARTHAG_x,EFG_O_x,EFG_D_x,TOR_x,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED
0,Gonzaga,WCC,37,33,123.4,89.9,0.9744,59.0,44.2,14.9,...,38.7,30.5,57.0,42.0,40.0,33.0,65.2,7.8,E8,2.0
1,Virginia,ACC,38,35,123.0,89.9,0.9736,55.2,44.7,14.7,...,34.9,28.6,49.7,40.1,35.2,30.8,58.4,10.0,R32,2.0
2,Duke,ACC,38,32,118.9,89.2,0.9646,53.6,45.0,17.5,...,39.8,23.9,55.9,46.3,38.7,31.4,66.4,10.7,Champions,1.0
3,North Carolina,ACC,36,29,120.1,91.4,0.9582,52.9,48.9,17.2,...,35.2,37.8,50.9,45.6,35.8,30.0,69.9,6.5,S16,4.0
4,Michigan,B10,37,30,114.6,85.6,0.9665,51.6,44.1,13.9,...,26.6,26.7,47.0,50.8,35.3,34.0,60.2,-2.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,Alcorn St.,SWAC,27,10,89.0,112.6,0.0628,45.7,52.7,24.1,...,37.5,39.9,43.3,50.9,28.4,38.2,66.9,-20.6,NaN,NaN
345,New Hampshire,AE,27,5,83.7,106.1,0.0613,44.0,51.5,18.4,...,36.1,42.6,45.9,45.6,37.4,31.1,64.2,-8.1,NaN,NaN
346,Chicago St.,WAC,30,3,88.5,117.3,0.0380,44.2,57.8,22.5,...,27.1,53.9,40.6,50.0,30.2,38.1,63.5,-17.7,NaN,NaN
347,Delaware St.,MEAC,29,6,84.3,112.2,0.0358,40.0,52.4,19.0,...,31.5,36.0,44.8,48.0,35.0,33.5,67.4,-10.7,NaN,NaN
348,Maryland Eastern Shore,MEAC,30,7,85.7,114.4,0.0346,43.5,54.4,20.7,...,47.0,41.1,48.9,52.6,38.2,32.4,64.9,-8.7,NaN,NaN

AttributeError: module 'pandas' has no attribute 'Dataframe'

# Load into database

In [12]:
# rds_connection_string = "postgres:postgres@localhost:5432/GroupDb"
rds_connection_string = "Jupyter:username:password@localhost:5432/Database"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [13]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "Jupyter"

(Background on this error at: http://sqlalche.me/e/e3q8)

In [ ]:
combineddf.to_sql(name='CombinedDF', con=engine, if_exists='append', index=False)

In [ ]:
engine.table_names()

In [3]:
data = pd.read_csv('FinalData.csv', low_memory=False)

In [4]:
data.head()

,Year,Round,Region Number,Region Name,Home_Seed,Home_Score,Home_Team,Away_Team,Away_Score,Away_Seed,Home_Conference,Away_Conference
0,2015,1,1,Midwest,6,56,Butler,Texas,48,11,BE,B12
1,2015,1,1,Midwest,3,69,Notre Dame,Northeastern,65,14,ACC,CAA
2,2015,1,1,Midwest,5,68,West Virginia,Buffalo,62,12,B12,MAC
3,2015,1,1,Midwest,2,75,Kansas,New Mexico St,56,15,B12,WAC
4,2015,1,1,Midwest,8,66,Cincinnati,Purdue,65,9,Amer,B10